hotel_managemen_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root_app.urls')),  # this line handles '/'
    path('hms/home/', include('root_app.urls')),
    path('hms/rooms/', include('hotel_room.urls')),
    path('hms/user/', include(('user_profile.urls', 'user_profile'))),
    path('hms/room-booking/', include('room_booking.urls')),
    path('hms/management/', include('management.urls')),
]

root_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home" ),
    path('contact', views.ContactView.as_view(), name="contact" ),
    path('about', views.AboutView.as_view(), name="about" ),
    path('search',views.SearchRoomView.as_view(), name='search'),

]

user_profile/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from user_profile.models import Account, Person, Address


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = Account
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = Account
        fields = ('email',)


class PersonForm(forms.ModelForm):
    # password = forms.CharField(max_length=12, widget=forms.PasswordInput())
    class Meta:
        model = Person
        fields = ['name', 'email']

class PersonForm2(forms.ModelForm):
    # password = forms.CharField(max_length=12, widget=forms.PasswordInput())
    class Meta:
        model = Person
        fields = "__all__"


class AccountForm(forms.ModelForm):
    # email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Account
        fields = ['password']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['person']
        

class ProfileForm(forms.Form):
    name = forms.CharField(max_length=64)
    email = forms.EmailField()
    phone = forms.CharField(max_length=16)
    account_type = forms.CharField(max_length=20, disabled=True)
    city = forms.CharField(max_length=50)
    country = forms.CharField(max_length=50)
    zip_code = forms.IntegerField()

templates/user/login.html
{% extends 'common/base.html' %}
{% block content %}
<main>
    <section>
        <div class="container pt-5">
            <h2 class="text-center">Please <span class="mr-pc">Log in</span> to the system</h2>
            <div class="row">
                <div class="col col-md-6 mx-auto p-1 p-md-5 user-login-form">
                    <form action="{% url 'user_profile:login' %}" method="post">
                        {% csrf_token %}
                        {% if error_msg %}
                        <div class="alert alert-danger" role="alert">
                            {{error_msg}}
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="col col-md-8">
                                <div class="form-group">
                                    <label for="id_{{person_form.email.name}}">Email address</label>
                                    <input required type="email" name="{{person_form.email.name}}"
                                        class="form-control border-info" id="id_{{person_form.email.name}}"
                                        aria-describedby="emailHelp" {% if person_form.email.value%}
                                        value="{{person_form.email.value}}" {%endif%} placeholder="Enter email">
                                    {{person_form.email.errors}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-md-8">
                                <div class="form-group">
                                    <label for="id_{{account_form.password.name}}">Password</label>
                                    <input required name="{{account_form.password.name}}" type="password"
                                        class="form-control border-info" id="id_{{account_form.password.name}}" {% if
                                        account_from.password.value %} value="{{account_form.password.value}}" {%
                                        endif%} placeholder="Password">
                                    {{account_form.password.errors}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col d-flex justify-content-center mt-md-3">
                                <button type="submit" class="btn mr-bgpc text-white px-md-5">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
</main>
{% endblock content %}

templates/user/profile.html
{% extends 'common/base.html' %}

{% block content %}
<main class="container my-5">
    <h2 class="text-center"><span class="mr-pc font-weight-bold">Profile</span> Summary</h2>
    <hr class="hr-bar mt-n2 rounded">
    <div class="row">
        {% if error_msg %}
        <div class="col-7">
            <div class="alert alert-danger" role="alert">
                {{error_msg}}
            </div>
        </div>
        {% endif %}
        <div class="col-7 col-md-6 mx-auto p-2 p-md-5 user-login-form">

            <form method="post" action="{% url 'user_profile:profile' %}">
                {%csrf_token%}
                <div class="form-group">
                    <label for="id_{{person_form.name.name}}">Name</label>
                    <input required type="text" class="form-control border-info" id="id_{{person_form.name.name}}"
                        name="{{person_form.name.name}}" value="{{person_form.name.value}}">
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="id_{{person_form.email.name}}">Email address</label>
                    <input required name="email" id="id_{{person_form.email.name}}" type="email" class="form-control border-info"
                        value="{{person_form.email.value}}">
                    {% if person_form.email.errors %}
                    <small id="emailHelp" class="form-text text-muted">
                        {{person_form.email.errors}}
                    </small>
                    {% endif %}
                    <!--  -->
                </div>
                <div class="form-group">
                    <label for="id_{{person_form.phone.name}}">Phone Number</label>
                    <input required name="phone" id="id_{{person_form.phone.name}}" type="tel" class="form-control border-info"
                        value="{{person_form.phone.value}}">
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="id_{{person_form.account_type.name}}">Account Type</label>
                    <input required readonly name="account_type" id="id_{{person_form.account_type.name}}" type="text"
                        class="form-control border-info" value="{{person_form.account_type.value}}">
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="id_{{address_form.city.name}}">City</label>
                    <input required name="{{address_form.city.name}}" id="id_{{address_form.city.name}}" type="text"
                        class="form-control border-info" {% if address_form.city.value %} value="{{address_form.city.value}}"
                        {%endif%}>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="id_{{address_form.country.name}}">Country</label>
                    <input required name="{{address_form.country.name}}" id="id_country" type="text"
                        class="form-control border-info" {% if address_form.city.value %} value="{{address_form.country.value}}"
                        {%endif%}>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="id_{{address_form.zip_code.name}}">Zip Code</label>
                    <input required name="{{address_form.zip_code.name}}" id="id_{{address_form.zip_code.name}}"
                        type="text" class="form-control border-info" {% if address_form.city.value %}
                        value="{{address_form.zip_code.value}}" {%endif%}>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>

                <!-- <div class="form-group">
                    <label for="id_password">Password</label>
                    <input readonly type="password" name="password" class="form-control" id="id_password" value="{{person.password}}">
                </div> -->

                <div class="row">
                    <div class="col d-flex justify-content-center mt-md-3">
                        <button type="submit" class="btn mr-bgpc text-white px-md-5">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</main>
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

templates/user/register.html
{% extends 'common/base.html' %}
{% block content %}
<main>
    <section>
        <div class="container pt-5">
            <h2 class="text-center">Please <span class="mr-pc">create</span> an account</h2>
            <div class="row">
                <div class="col col-md-6 mx-auto p-2 p-md-5 user-registration-form">
                    <form action="{% url 'user_profile:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_{{person_form.name.name}}">Name</label>
                            <input required type="text" name="{{person_form.name.name}}" class="form-control border-info"
                                id="id_{{person_form.name.name}}" {% if person_form.name.value%}
                                value="{{person_form.name.value}}" {%endif%} placeholder="Enter name">
                        </div>
                        <div class="form-group">
                            <label for="id_{{person_form.email.name}}">Email address</label>
                            <input required type="email" name="{{person_form.email.name}}" class="form-control border-info"
                                id="id_{{person_form.email.name}}" aria-describedby="emailHelp" 
                                {% if person_form.email.value%} value="{{person_form.email.value}}" {%endif%}
                                placeholder="Enter email">
                            {% if person_form.email.errors %}
                            <div class="alert alert-danger mt-2" role="alert">
                                {{person_form.email.errors}}
                            </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_{{account_form.password.name}}">Password</label>
                            <input required name="{{account_form.password.name}}" type="password" class="form-control border-info"
                                id="id_{{account_form.password.name}}" {% if account_from.password.value %}
                                value="{{account_form.password.value}}" {% endif %} placeholder="Password">
                                {% if account_form.password.errors %}
                                <div class="alert alert-danger mt-2" role="alert">
                                    {{account_form.password.errors}}
                                </div>
                                {% endif %}
                            
                        </div>

                        <div class="row">
                            <div class="col d-flex justify-content-center mt-md-3">
                                <button type="submit" class="btn mr-bgpc text-white px-md-5">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock content %}